# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ObjectStorage' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjectStorage

  target 'ObjectStorageTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ObjectMapper', '~> 1.3.0'
  end

end
